// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

declare namespace Contentful {
  export interface IAboutFields {
    /** profile */
    profile: Document;
  }

  export interface IAbout extends Entry<IAboutFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "about";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export interface IIllustrationsFields {
    /** image */
    image: Asset;

    /** title */
    title: string;
  }

  export interface IIllustrations extends Entry<IIllustrationsFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "illustrations";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export interface IWorksFields {
    /** title */
    title: string;

    /** description */
    description: Document;

    /** images */
    images: Asset[];
  }

  export interface IWorks extends Entry<IWorksFields> {
    sys: {
      id: string;
      type: string;
      createdAt: string;
      updatedAt: string;
      locale: string;
      contentType: {
        sys: {
          id: "works";
          linkType: "ContentType";
          type: "Link";
        };
      };
    };
  }

  export type CONTENT_TYPE = "about" | "illustrations" | "works";

  export type LOCALE_CODE = "ja";

  export type CONTENTFUL_DEFAULT_LOCALE_CODE = "ja";
}

export as namespace Contentful;
export = Contentful;
